### ISSUE TITLE
Issue with building software without database URI

### ISSUE THREAD

**Issue by DanielXu222** [CocoLee2/SaverChef#8]
We don't have a database URI so we were unable to build this project. The app.py file won't run the backend unless we have set up a database URI, and we are missing instructions on how to obtain one.

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified app.py to use SQLite database by default and updated README.md with instructions on how to set up and run the project, including database configuration.

You can review changes in this commit: https://github.com/lattaai13/CocoLee2-SaverChef-8/commit/26a5f92f30b74f1523d73ce6abf46a3c787475aa.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by boyulz** [comment]
Hi Daniel! Thank you for reporting the issue! We revised README.md to make sure developers could easily use PostgreSQL even they never used before. Following the new README.md, you should be able to set up a database URI in 5 mins.
